language: node_js
node_js:
  - lts/*
cache: npm
script:
  - npm run test:unit
  - npm run build-app
deploy:
  provider: pages
  local_dir: dist-app
  skip_cleanup: true
  github_token: $GITHUB_TOKEN

  on:
    branch: master
